# tasks:
#   - init: 'echo "TODO: Replace with init/build command"'
#     command: 'echo "TODO: Replace with command to start project"'

tasks:
  - init: |
      npm install -g firebase-tools
      cd /workspace/www.udonko.net/firebase
      npm install
    command: |
      cd /workspace/www.udonko.net/firebase
      firebase login:ci --no-localhost
